def start(directory, name, width, height):
    filename = directory + "/report/" + name
    file = open(filename, "w")

    file.write("<html>\n")
    file.write("<head>\n")
    file.write("<title>Phaenotyp | Report</title>\n")
    file.write("Phaenotyp | Report <br>\n")
    file.write("<br>\n")
    file.write("<a href='axial.html'>axial</a> |\n")
    file.write("<a href='moment_y.html'>moment_y</a> |\n")
    file.write("<a href='moment_z.html'>moment_z</a> |\n")
    file.write("<a href='shear_y.html'>shear_y</a> |\n")
    file.write("<a href='shear_z.html'>shear_z</a> |\n")
    file.write("<a href='torque.html'>torque</a>\n")
    file.write("<br>\n")
    #file.write("<a href='Wy.html'>Wy</a> |\n")
    #file.write("<a href='WJ.html'>WJ</a> |\n")
    #file.write("<a href='long_stress.html'>long_stress</a> |\n")
    #file.write("<a href='tau_shear.html'>tau_shear</a> |\n")
    #file.write("<a href='tau_torsion.html'>tau_torsion</a> |\n")
    #file.write("<a href='sum_tau.html'>sum_tau</a> |\n")
    #file.write("<a href='sigmav.html'>sigmav</a> |\n")
    #file.write("<a href='sigma.html'>sigma</a> |\n")
    #file.write("<br>\n")
    file.write("<a href='max_long_stress.html'>max_long_stress</a> |\n")
    file.write("<a href='max_tau_shear.html'>max_tau_shear</a> |\n")
    file.write("<a href='max_tau_torsion.html'>max_tau_torsion</a> |\n")
    file.write("<a href='max_sum_tau.html'>max_sum_tau</a> |\n")
    file.write("<a href='max_sigmav.html'>max_sigmav</a> |\n")
    file.write("<a href='max_sigma.html'>max_sigma</a>\n")
    file.write("<br>\n")
    #file.write("<a href='deflection.html'>deflection</a> |\n")
    #file.write("<a href='overstress.html'>overstress</a>\n")
    file.write("<br>\n")
    file.write("<br>\n")
    file.write("</head>\n")
    file.write("\n")
    file.write("<style>\n")
    file.write("* {font-family: sans-serif;}\n")
    file.write("a:link {color: rgb(0, 0, 0); background-color: transparent; text-decoration: none;}\n")
    file.write("a:visited {color: rgb(0,0,0); background-color: transparent; text-decoration: none;}\n")
    file.write("a:hover {color: rgb(0,0,0); background-color: transparent; text-decoration: underline;}\n")
    file.write("a:active {color: rgb(0,0,0); background-color: transparent; text-decoration: underline;}\n")
    file.write("</style>\n")
    file.write("\n")
    file.write("<body style='margin : 0px; overflow: scroll;'>\n")
    file.write("<svg ")
    file.write("width='" + str(width) + "'")
    file.write("height='" + str(height) + "'>\n")
    file.write("\n")

    return file

def line(file, x1, y1, x2, y2, width, color):
    file.write("<line ")
    file.write("x1='" + str(x1) + "' ")
    file.write("y1='" + str(y1) + "' ")
    file.write("x2='" + str(x2) + "' ")
    file.write("y2='" + str(y2) + "' ")
    file.write("style='stroke:rgb(" + color + "); ")
    file.write("stroke-width:" + str(width))
    file.write("'/>\n")

def text(file, x, y, text, anchor):
    file.write("<text text-anchor=")
    file.write("'" + anchor + "' ")
    file.write("x='" + str(x) + "' ")
    file.write("y='" + str(y) + "'>")
    file.write(str(text))
    file.write("</text>\n")

def text_link(file, x, y, text):
    file.write("<a xlink:href=")
    file.write("'" + str(text) + "' ")
    file.write("target='_self'>")
    file.write("<text ")
    file.write("x='" + str(x) + "' ")
    file.write("y='" + str(y) + "'>")
    file.write(str(text) +  "</text>")
    file.write("</a>\n")

def end(file):
    file.write("</svg>\n")
    file.write("</body>\n")
    file.write("</html>\n")
    file.close()
